name: cos-sgwb
channels:
  - conda-forge

dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - pandas
  - astropy
  - bilby
  - dynesty
  - gwpy<4
  - pip
  - pip:
      - pygwb